#!/usr/bin/env python3
"""Pick calculation puzzles from the Lichess puzzle database into sessions/puzzles.js.

    curl -o ~/.cache/zwischenzug/puzzles/lichess_db_puzzle.csv.zst https://database.lichess.org/lichess_db_puzzle.csv.zst
    python3 scripts/build_puzzles.py

Lichess puzzle database: CC0 (https://database.lichess.org/#puzzles). Kept only: lines of at
least 5 plies after the opponent's move (something to calculate, not a one-mover), no short
mates, popular and well-rated, about PER_BAND per 100-point band. At the edges (below 900,
2500 and up) the strict filter finds too few, so a looser one (LOOSE_*) fills those bands. Every
puzzle already in sessions/puzzles.js stays, so saved days and progress keep their positions.
Every line is replayed with python-chess. Output: window.PATH_PUZZLES = [{id, r, fen, line, themes}] — fen is the position
after the opponent's first move, line is the solution in SAN, both sides.
"""
from __future__ import annotations

import csv
import io
import json
import pathlib
import random
import subprocess

import chess

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = pathlib.Path.home() / ".cache" / "zwischenzug" / "puzzles" / "lichess_db_puzzle.csv.zst"
OUT = ROOT / "sessions" / "puzzles.js"
LOW, HIGH, BAND, PER_BAND = 700, 3000, 100, 150
MIN_PLIES = 5
SKIP = {"mateIn1", "mateIn2", "oneMove", "short"}
MIN_POPULARITY, MIN_PLAYS, MAX_DEVIATION = 85, 2000, 80
LOOSE_POPULARITY, LOOSE_PLAYS, LOOSE_DEVIATION = 80, 300, 90


def candidate(row: dict) -> dict | None:
    themes = row["Themes"].split()
    if SKIP & set(themes):
        return None
    pop, plays, dev = int(row["Popularity"]), int(row["NbPlays"]), int(row["RatingDeviation"])
    if pop < LOOSE_POPULARITY or plays < LOOSE_PLAYS or dev > LOOSE_DEVIATION:
        return None
    strict = pop >= MIN_POPULARITY and plays >= MIN_PLAYS and dev <= MAX_DEVIATION
    rating = int(row["Rating"])
    if not LOW <= rating < HIGH:
        return None
    uci = row["Moves"].split()
    if len(uci) - 1 < MIN_PLIES:
        return None
    board = chess.Board(row["FEN"])
    board.push_uci(uci[0])              # the opponent's move that sets the puzzle
    fen = board.fen()
    line = []
    for move in uci[1:]:
        m = chess.Move.from_uci(move)
        if m not in board.legal_moves:
            return None
        line.append(board.san(m))
        board.push(m)
    shown = [t for t in themes if t not in ("long", "veryLong", "crushing", "advantage", "middlegame", "endgame",
                                            "opening", "master", "masterVsMaster", "superGM")]
    return {"id": row["PuzzleId"], "r": rating, "fen": fen, "line": line, "themes": shown[:4],
            "long": "veryLong" in themes or "long" in themes, "strict": strict}


def kept() -> set[str]:
    if not OUT.exists():
        return set()
    text = OUT.read_text()
    return {p["id"] for p in json.loads(text[text.index("["): text.rindex("]") + 1])}


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit(f"missing {SOURCE} — download it first (see the docstring)")
    old = kept()
    bands: dict[int, list[dict]] = {}
    proc = subprocess.Popen(["zstd", "-dc", str(SOURCE)], stdout=subprocess.PIPE)
    for row in csv.DictReader(io.TextIOWrapper(proc.stdout, encoding="utf-8")):
        p = candidate(row)
        if p:
            bands.setdefault((p["r"] - LOW) // BAND, []).append(p)
    proc.wait()
    rng = random.Random(20261001)      # same input, same selection
    picked = []
    for band in sorted(bands):
        pool = bands[band]
        keep = [p for p in pool if p["id"] in old]
        rest = [p for p in pool if p["id"] not in old]
        strict = [p for p in rest if p["strict"]]
        if len(strict) >= PER_BAND * 3:
            rest = strict
        # strict first, long lines first, then a fixed order
        rest.sort(key=lambda p: (not p["strict"], not p["long"], p["id"]))
        top = rest[: PER_BAND * 3]
        rng.shuffle(top)
        picked += sorted(keep + top[: max(0, PER_BAND - len(keep))], key=lambda p: p["r"])
    missing = old - {p["id"] for p in picked}
    if missing:
        raise SystemExit(f"{len(missing)} puzzles from the old set are gone, e.g. {sorted(missing)[:3]}")
    for p in picked:
        del p["long"], p["strict"]
    body = json.dumps(picked, ensure_ascii=False, separators=(",", ":"))
    OUT.write_text("// Generated by scripts/build_puzzles.py from the Lichess puzzle database (CC0).\n"
                   f"window.PATH_PUZZLES = {body};\n")
    print(f"{len(picked)} puzzles in {len(bands)} bands → {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
